export const posts = [
  "Just spilled coffee all over my laptop... Great start to the day! #MondayBlues",
  "If you could have any superpower, what would it be? I'm torn between flying and invisibility.",
  "Why do weekends go by so fast? Can we petition for a three-day weekend, please?",
  "Does anyone else hit snooze a million times in the morning? Asking for a friend. #NotAMorningPerson",
  "Pro tip: Don't grocery shop when you're hungry. I just bought way too many snacks.",
  "Watching old movies and realizing how much technology has changed. Remember VHS tapes?",
  "I can't decide if I need a coffee, a nap, or a vacation. Maybe all three?",
  "Ever have one of those days where everything goes wrong? Today is that day.",
  "The best part of working from home is definitely the unlimited snacks. And the worst? The distractions.",
  "Does anyone else have a love-hate relationship with social media? It's a blessing and a curse.",
  "Why is adulting so hard? They didn't teach us this in school. #LifeSkills",
  "When your dog understands your mood better than most people. #DogLife",
  "Is it just me, or does time fly when you're binge-watching your favorite series?",
  "Note to self: Never trust the weather forecast. It's always wrong.",
  "Trying to eat healthy but chocolate keeps calling my name. #Struggles",
  "The feeling when you finally finish a project you've been working on forever. #Accomplishment",
  "How do people keep their houses so clean? Mine looks like a tornado hit it. #MessyLife",
  "Feeling nostalgic for the days when the biggest decision was which cartoon to watch.",
  "Can someone invent a device that tells you where you left your keys? Asking for myself.",
  "Who else is guilty of staying up way too late because of one more episode syndrome?",
  "Just saw a double rainbow! Nature never ceases to amaze me. #Beautiful",
  "If only there were more hours in a day... So much to do, so little time.",
  "Remember when we thought 2020 was going to be our year? Oh, how naive we were.",
  "Why do cats always sit on the one thing you need to use? It's like they know.",
  "Feeling grateful for the little things in life, like a good cup of tea and a cozy blanket.",
  "Why do we always crave the things we can't have? Life is funny that way.",
  "To all the people who can parallel park perfectly: I salute you. #ParkingStruggles",
  "Is there anything better than the smell of freshly baked cookies? I think not.",
  "Can someone explain why I have 20 tabs open and I still can't find what I'm looking for?",
  "The struggle of finding a good show to watch after finishing an amazing series. Recommendations welcome!",
];

export const batmanPosts = [
  "Patrolling Gotham tonight. Looks like someone's up to no good at Ace Chemicals. Time to swing into action. 🦇 #DarkKnight",
  "Just had to rescue a cat stuck in a tree. Even Batman does community service sometimes. 🐱 #GothamHero",
  "Alfred just told me my cape needs dry cleaning. Apparently, it smells like fear. Who knew? 🧥 #GothamFashion",
  "Batmobile got a flat tire on the way to the Batcave. Note to self: Check the tires more often. 🚗 #SuperheroProblems",
  "Just had a staring contest with Joker. He blinked first. Victory for justice! 👀 #NeverBlinks",
  "Crime rates are down in Gotham this month. Maybe villains are taking summer vacations too? 🌞 #PeacefulGotham",
  "Working on some new gadgets in the Batcave. Utility belt is getting an upgrade! 🔧 #AlwaysPrepared",
  "Found a hidden door in Wayne Manor. Turns out it leads to the old Batcave. Time to redecorate! 🏰 #SecretPassages",
  "Had to bribe Commissioner Gordon with coffee to get him to stop shining the Bat-signal. ☕ #LateNightHeroics",
  "Thinking about getting a sidekick. Applications now open! Must like bats and not be afraid of heights. 🦇 #NeedHelp",
];

export const supermanPosts = [
  "Saved a falling satellite today. Just another day at the office. 🛰️ #ManOfSteel",
  "Had to fix the Daily Planet coffee machine again. It's not as easy as saving the world, but someone's gotta do it. ☕ #ReporterLife",
  "Got a new fan mail today. Turns out someone wants to be just like me. That's a lot of pressure! 💌 #SuperFan",
  "Stopped a runaway train from derailing. Faster than a speeding locomotive, they say! 🚆 #TrainRescue",
  "Just finished a game of basketball with the kids in Metropolis. They said I should go easy on them. 😅 #FriendlyCompetitions",
  "Helped an old lady cross the street today. Sometimes being super means doing the little things too. 👵 #SuperKindness",
  "Met Lex Luthor at a charity gala. We had a staring contest. Let's just say I won. 👀 #SuperiorStare",
  "Caught a falling plane mid-air. Pilots said I was faster than air traffic control. 🛩️ #SkyRescue",
  "Spent the day at the Fortress of Solitude. Krypto keeps stealing my cape. It's a tough life being Superman's dog. 🐕 #SuperPets",
  "Thinking of starting a podcast about life as Superman. What do you think? 🎙️ #SuperTalk",
];

export const wonderWomanPosts = [
  "Trained with the Amazons today. Sometimes the old ways are the best ways. 🏹 #AmazonWarrior",
  "Visited Themyscira after a long mission. Home always brings peace. 🏝️ #IslandLife",
  "Talked diplomacy with world leaders at the UN today. Finding common ground is a superpower in itself. 🌍 #PeaceAmbassador",
  "Stopped a bank robbery using the Lasso of Truth. Turns out honesty is the best policy. 💰 #LassoPower",
  "Attended a gala in Paris. Wonder what the fashion trends will be in the next century? 🗼 #TimelessStyle",
  "Helped rescue endangered species in the Amazon rainforest. Nature needs heroes too. 🌿 #NatureGuardian",
  "Practiced lasso tricks with Steve Trevor. He's getting better at tying knots! 🪢 #LassoSkills",
  "Had a spar with Artemis today. She's always pushing me to be my best. 🥊 #AmazonChallenge",
  "Explored a new archaeological site in Greece. Uncovering ancient secrets is always thrilling. 🏺 #HistoryExplorer",
  "Thinking of starting a book club with the other Amazons. What should our first read be? 📚 #WonderReads",
];

export const comments = [
  "Absolutely agree with this! I've been thinking the same thing for a while now.",
  "Thanks for sharing this, it really made my day better.",
  "This is such a relatable post, I can't even explain how much!",
  "Wow, never thought of it that way. You've opened my eyes!",
  "Couldn’t have said it better myself!",
  "I totally needed to hear this today. Thank you!",
  "This made me laugh out loud, thanks for the humor!",
  "I'm glad I'm not the only one who feels this way.",
  "You always seem to say what I'm thinking!",
  "So true! This is exactly what I was talking about yesterday.",
  "This is so accurate it hurts!",
  "Just what I needed to see today. Thanks for posting!",
  "I can definitely relate to this, happens to me all the time.",
  "Haha, this is so funny and true!",
  "Great point! Thanks for sharing your thoughts.",
  "This is so spot on! Couldn't have said it better.",
  "Wow, this really resonates with me.",
  "Thank you for sharing this. It really put things into perspective.",
  "Haha, this is hilarious! You made my day!",
  "This is exactly how I feel about this situation.",
  "Thanks for the positivity, much needed today!",
  "Couldn't agree more with you!",
  "So true! Thanks for pointing this out.",
  "This is the funniest thing I've read all day!",
  "Absolutely spot on, I completely agree.",
  "Thanks for sharing this, it's very insightful.",
  "This made me laugh! Thanks for the humor.",
  "I can relate to this on so many levels!",
  "Thanks for posting this, it's just what I needed.",
  "This is so true, happens to me all the time.",
  "So glad someone else feels this way too!",
  "Thanks for the laugh, I needed that today.",
  "This is such a great point, thanks for sharing.",
  "I'm so glad you posted this, it's so relatable!",
  "This is exactly what I was thinking!",
  "You always know how to make me laugh!",
  "Such a great perspective, thank you for sharing.",
  "This is so funny and true, I love it!",
  "Absolutely agree with you on this one.",
  "This is so accurate, thanks for posting!",
  "Just what I needed to read today, thank you.",
  "I can totally relate to this!",
  "Thanks for the insight, it's very helpful.",
  "This is the best thing I've read all day!",
  "You always have the best posts!",
  "Thanks for sharing this, it's so true!",
  "I can't stop laughing, this is so funny!",
  "So glad I'm not the only one who thinks this.",
  "Thanks for the positivity, much appreciated!",
  "This is such a great reminder, thank you.",
];

export const replies = [
  "Couldn't agree more, this is so true!",
  "Haha, yes! I feel the same way.",
  "Exactly! You hit the nail on the head.",
  "Totally, I was thinking the same thing.",
  "This is so accurate, thanks for pointing it out.",
  "Haha, right? This made me laugh too.",
  "Absolutely! I was just talking about this.",
  "So true, thanks for sharing your thoughts.",
  "Haha, I can relate to this so much.",
  "Yes! This is exactly how I feel.",
  "Couldn't have said it better myself!",
  "This is spot on, thanks for sharing.",
  "Haha, glad I'm not the only one who thinks this.",
  "Exactly! This is so relatable.",
  "This made me laugh, thanks for posting.",
  "Totally agree with you on this.",
  "This is so true, thanks for the insight.",
  "Haha, yes! This is hilarious.",
  "Absolutely! Thanks for pointing this out.",
  "So true, this is exactly what I was thinking.",
  "Haha, glad someone else feels the same way.",
  "Yes! This is so accurate.",
  "This made me smile, thanks for sharing.",
  "Absolutely agree, this is spot on.",
  "Haha, right? This is so funny.",
  "Yes! This is so true.",
  "Totally! This is exactly how I feel.",
  "This is so accurate, thanks for posting.",
  "Haha, this is so funny and true.",
  "Absolutely agree with this!",
];

export const bios = [
  "Coffee addict ☕ | Avid reader 📚 | Cat lover 🐱",
  "Tech enthusiast 💻 | Gamer 🎮 | Always exploring new ideas 💡",
  "Traveler 🌍 | Foodie 🍕 | Music lover 🎵 | Dream big, work hard!",
  "Digital nomad 🗺️ | Photographer 📸 | Capturing moments one click at a time",
  "Fitness freak 🏋️ | Healthy lifestyle advocate 🍏 | Let's stay fit together!",
  "Bookworm 📖 | Aspiring writer ✍️ | Lover of all things magical ✨",
  "Dog mom 🐶 | Plant lover 🌿 | Living life one day at a time",
  "Software developer 💻 | Problem solver 🧩 | Code is my art 🎨",
  "Sports fan 🏀 | Music junkie 🎧 | Always up for a challenge!",
  "Artist 🎨 | Dreamer 💭 | Believer in the power of imagination",
  "Nature lover 🌲 | Adventure seeker 🧗 | Finding beauty in simplicity",
  "Chef in the making 👩‍🍳 | Culinary explorer 🍲 | Food is my passion",
  "Fashion enthusiast 👗 | Trendsetter 👠 | Style is a way to say who you are",
  "History buff 📜 | Trivia master 🎓 | Collector of useless knowledge 🧠",
  "Environmental advocate 🌍 | Green thumb 🌱 | Let's save the planet together",
  "Aspiring musician 🎸 | Coffee lover ☕ | Always chasing the next adventure",
  "Cat dad 🐱 | Book lover 📚 | Finding joy in the little things",
  "DIY enthusiast 🔨 | Craft lover ✂️ | Creating one project at a time",
  "Movie buff 🎬 | Pop culture nerd 🤓 | Let's talk cinema!",
  "Science geek 🔬 | Space enthusiast 🚀 | Curiosity never killed this cat",
  "Fitness guru 🏋️ | Health nut 🥗 | Inspiring others to live their best life",
  "Tech junkie 💻 | Gadget guru 📱 | Always on the cutting edge",
  "Traveler ✈️ | Culture enthusiast 🌍 | Exploring the world one city at a time",
  "Yoga lover 🧘 | Meditation practitioner 🌿 | Peace, love, and zen",
  "Dog lover 🐕 | Nature enthusiast 🌳 | Finding peace in the great outdoors",
  "Gaming nerd 🎮 | Anime fan 🍥 | Living in a world of pixels and dreams",
  "Fitness enthusiast 🏃 | Marathon runner 🏅 | Always striving for the best",
  "Aspiring chef 👨‍🍳 | Food blogger 🍔 | Cooking up something delicious",
  "Music lover 🎶 | Vinyl collector 📀 | Let's spin some tunes",
  "Dream chaser 🌟 | Goal setter 🎯 | Making every day count",
];

export const batmanBio =
  "Night owl 🦇 | Billionaire by day 💵, vigilante by night 🌙 | Professional brooder 🖤 | Always forgetting where I parked the Batmobile 🏎️ | Alfred's favorite headache 🧠 | #NotARichGuyWithIssues";
export const supermanBio =
  "Mild-mannered reporter by day 📰, superhero by...well, all the time 🦸‍♂️ | Faster than a speeding bullet 🚀 | Can bench press a planet 🌍 | Krypton’s last son 🌌 | Weakness: kryptonite and bad puns 💎 | #NotJustACape";
export const wonderWomanBio =
  "Amazonian warrior princess 🏹 | Ambassador of peace ✌️ | Fierce protector of Earth 🌍 | Can lasso the truth out of anyone 🪢 | Daughter of Zeus ⚡️ | #NotJustATiara";
